### ISSUE TITLE
疑問点

### ISSUE THREAD

**Issue by nnk-ymmt** [nnk-ymmt/30DAYS-TRIAL.Copy#1]
1. input要素のvalue属性にスペースで左側の余白を調整しているが(inputの中の文字の左側)、これでもいいのか。
推奨される表記方法はあるのか。paddingを付けたりできるのか。

1. containerにheight無しでも一応上手くいっているが、無くてもいいのか、通常付けるものなのか。margin: autoが適用されているがブロック要素になっているのか。

1. cssのセレクタ表記方法　他にliダグがない場合、div class="header-list"で囲まなくてもul class="header-list"と直接親要素にclassを付けてしまえばいいのか。

1. .header-list liの頭部分header-listは不要か

1. liでaタグを囲っている時はfont-sizeをどちらで指定するのか

1.  .header-list ulにmargin: autoで作動しているがheightはいらないのか。
ディベロッパーツールではulがheightを持たないのでliを囲んでいないように見えるがいいのか。

1. 何故.top-messageはtext-align: centerの方がうまくいくのか、ブロック要素にはなっていないのか。ブロック要素だと認識している為margin: 0 autoでないのが疑問。

1. .courses imgはimgだからインライン要素ではないのか（ブロック要素になっているからmargin: autoで作動しているのか？)

1. transform: translate(-50%, -50%)の意味がわからない。どこ起点に-50%になっているのか。

1. ディベロッパーツールで見るとtop-messageが浮いているのは何故。

1. スマホ版ではfloatでheader-listを調整できないのは何故。floatでの表記方法が知りたい。

1. ブロック要素に指定するmargin: 0 autoは0がmargin: autoでほぼ代用できているが0必要か？

**Comment by ryota-nakano** [comment]
twitterで頑張ってらっしゃったので、超真面目に答えます。
@nakanotep

1. できます。inputにクラスをつけるなどして、paddingを付ければOKです。

2. `.container`は中身の要素に合わせて高さが可変になって欲しいので指定してはいけません。どうしても指定するなら`height:auto;`です。それと`div`なので初めからブロック要素です。

3. その通りです。他にli要素があったとしても、直接親要素であるulにクラスをつけてしまえばもはやdivで囲う必要はないですね。

4. その`.header-list`は今回に限り無くてもいいのですが、もし`.header-list`の中以外にもliがあった場合（.footer-list liなど）そちらにもスタイルが当たってしまい、カオス状態になります。

5. どちらで指定するという決まりはないです。CSSは、基本的に親要素のスタイルを子要素が継承（inherit）します。

6. これも、2の`.container`と一緒で中身の要素によって高さが変わって欲しいので、heightつけない方がいいです。ulがheightを持たないのでliを囲んでいないように見えるのはclearfixですね。ulにoverflowをかけると簡単に解決します。参考：https://web-camp.io/magazine/archives/27842

7. これはブロック要素なのですが、`.top-message`に`position: absolute;`が当たっているので`margin: 0 auto`は効きません。`text-align:center;`は`.top-message`の中でテキストが中央寄せになっているだけです。`.top-message`は絶対配置（absolute）で中央になっています。

8. style.cssの263行目でdisplay:blockになってます。

9. 起点というか、横方向に-50%、縦方向に-50%となってますね。この場合の%は自分自身のサイズに対してです。

10. これは、style.cssの54行目。`.top-message`が画面に対して絶対配置になっているからで、ディベロッパーツールを開いた際にブラウザの画面が狭くなっているからですね。

11. floatでもかけます。`.header-list{display:table;margin:auto;}`liはそのままfloat。

12. これは、上下のmarginが不要ならautoだけで良いです。
